[[redirects]]
  from = "/*"
  to = "https://www.notion.so/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/ganbare-chiba"
  to = "https://www.notion.so/15-9049a61e1dcd46c585851b0f82e4c1fe"
  status = 200
  force = true
